# Database (development)
DB_NAME=sproutly

# Trefle API (plant search)
TREFLE_TOKEN=usr-z40u-7Xb5sWcaYAHSXoZ_rcb33IfN2mHkZt_pkqonxI

# JWT token settings
ISSUER=Sproutly
TOKEN_EXPIRE_TIME=86400000
SECRET_KEY=your-secret-key-min-32-chars-long-for-hs256

# Optional: bootstrap admin user (created on startup if missing; default: admin@test.dk / admin123)
# ADMIN_EMAIL=admin@test.dk
# ADMIN_PASSWORD=admin123
