name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            set -e

            cd /root/backend
            git pull origin main

            docker compose down
            docker compose up -d --build --force-recreate

            cd /root/backend/frontend
            npm install
            npm run build

            rm -rf /var/www/sproutly/*
            cp -r dist/* /var/www/sproutly/

            systemctl reload nginx
